batch_size: 32
dataset: input_data
early_stopping:
  min_delta: 0.01
  mode: min
  monitor: val_loss
  patience: 50
  verbose: 1
epochs: 2000
extra_verbose: 1
input_data_folder: /content/gdrive/My Drive/code_to_train_and_use_new_models/model_with_dense_layer_deeper/data/
learning_rate: 0.001
loss_path: /content/gdrive/My Drive/code_to_train_and_use_new_models/model_with_dense_layer_deeper/wartem/losses/
model_checkpoint:
  mode: min
  monitor: val_loss
  save_best_only: true
model_path: /content/gdrive/My Drive/code_to_train_and_use_new_models/model_with_dense_layer_deeper/wartem/models/
n_channels: 1
num_inits: 1
num_warps: 50
params_dump_path: /content/gdrive/My Drive/code_to_train_and_use_new_models/model_with_dense_layer_deeper/wartem/params_dump/
rep_length: 10
resume_check: true
shuffle: true
validation_split: 0.8
verbosity: 0
warping: copy
point: true
